GET http://localhost:4000/healthcheck

###
GET http://localhost:4000/heroes/2

###
POST http://localhost:4000/heroes
Content-Type: application/json

{
	"name": "Catwoman",
	"canFly": false,
	"firstSeen": "2016-03-01T00:00:00Z",
	"realName": "Selina Kyle",
	"abilities": ["acrobatics", "marksman", "stealth"]
}

###
GET http://localhost:4000/error

###
GET http://localhost:4000/panic-in-goroutine

###
GET http://localhost:4000/user
Authorization: Bearer Rainer

###
# Return all heroes
GET http://localhost:4000/heroes?pageSize=100&sort=name

###
GET http://localhost:4000/heroes?page=2&pageSize=10&sort=name
